# Configuration file
# Generated on 6/25/26 3:21 AM

####################
# block 
####################

block {
   machine=205
   mill=208
   resources=198
   soil=197
}

####################
# general 
####################

general {
   # set to false if apiaries should output all items regardless of side a pipe is attached to
   apiary.sidesensitive=false
   # change breeding modes here. possible values NORMAL, EASY, HARDCORE, FTB
   beebreeding.difficulty=NORMAL
   # set to true to track beebreeding globally instead of per single world. will not merge past histories!
   beebreeding.history.unified=false
   # add additional flower blocks for apiaries here in the format id:meta. separate blocks using ';'. will be treated like vanilla flowers. not recommended for flowers implemented as tile entities.
   beekeeping.flowers.custom=
   # set to false to disable crafting recipe for bronze
   crafting.bronze.enabled=true
   # set to false to disable crafting recipes for all farms (harvesters and planters)
   crafting.farms.enabled=true
   # set to false to disable crafting recipes for stamps
   crafting.stamps.enabled=true
   # set to true to make dungeon loot generated by forestry rarer
   difficulty.dungeonloot.rare=false
   # set to true to clear chromosomes which contain invalid alleles. might rescue your save if it is crashing after removal of a bee addon.
   genetics.invalid.chromosome.clearing=false
   # set to false if harvesters should output all harvested products regardless of side a pipe is attached to
   harvesters.sidesensitive=true
   # leaving this enabled will cycle the list of active players PER INGAME TICK to check for resupply via backpack. you want to set this to false on busy servers.
   performance.backpacks.resupply=true
   # set to false if farms should output all harvested products regardless of side a pipe is attached to
   planters.sidesensitive=true
   power.framework=forestry.energy.BioPowerFramework
   # set to false to disable particle fx on slower machines
   presentation.particleFX.enabled=true
   # higher numbers increase working speeds of harvesters but also increase cpu load.
   throttle.harvester=200
   # higher numbers increase working speeds of planters but also increase cpu load.
   throttle.planter=10
   # set to false to disable apple pickup by appropriate harvesters
   tweaks.apple.pickup.enabled=true
   # set to true to disable energy statistics on energy consumers.
   tweaks.energystat.disabled=true
   # set to true to disable hints on machine and engine guis.
   tweaks.hints.disabled=false
   # set to false to disable the mail alert box
   tweaks.mailalert.enabled=true
   # set to true to disable displaying liquid amounts in tank tooltips.
   tweaks.tooltip.liquidamount.disabled=true
   # set to false to force forestry to skip generating own apatite ore blocks in the world
   world.generate.apatite=true
   # set to false to force forestry to skip generating beehives in the world
   world.generate.beehives=true
   # set to false to force forestry to skip generating own copper ore blocks in the world
   world.generate.copper=true
   # set to false to force forestry to skip generating own tin ore blocks in the world
   world.generate.tin=true
}

####################
# item 
####################

item {
}

