# Configuration file
# Generated on 6/25/26 6:19 AM

####################
# block 
####################

block {
}

####################
# general 
####################

general {
   classname.items=forestry.api.ForestryItem
}

####################
# item 
####################

item {
   propolisPipe=14000
}

